### ISSUE TITLE
Set up automatic link checking

### ISSUE THREAD

**Issue by kemitchell** [indieopensource/indieopensource.com#1]
htmlproofer?

**Comment by SKalt** [comment]
I've been loving https://github.com/lycheeverse/lychee/, which has a convenient and schedulable Github Action. Want me to throw in a PR?

**Comment by kemitchell** [comment]
Thanks for mentioning Lychee. I've added to my list to check out when I'm back from vacation.

I should have closed this issue a long time ago, since I've long since been checking links for this and other websites of mine with cron jobs, as an HTTP client, rather than by running on sources. [linkchecker](https://linkchecker.github.io/linkchecker/) has done the job.
