### ISSUE TITLE
Broken link for "form paid license agreement"

### ISSUE THREAD

**Issue by anseljh** [indieopensource/indieopensource.com#10]
On the ["Private Licensing" page](https://indieopensource.com/private-licenses), the second paragraph reads:

> Indie Open Source maintains a form paid license agreement as a place to start. But there are a few decisions you need to make, with your particular project and customers in mind.

The text "form paid license agreement" links to `/forms/paid-license`, but that gives a 404.

**Comment by kemitchell** [comment]
@anseljh thanks so much. My link checking cron job should have caught this!
